---
- hosts: medshake
  become: true
  vars_files: secrets.yml

  tasks:
    - name: "Set timezone to {{ timezone }}"
      timezone:
        name: "{{ timezone }}"

    - name: Install packages
      apt:
        name: "{{ msehrPackages }}"
        update_cache: true
        state: present

    - name: UFW configuration
      ufw:
        state: enabled
        rule: allow
        name: '{{ item }}'
      loop:
        - OpenSSH
        - WWW Full

    - name: Override unattended-upgrades configuration
      template:
        src: templates/80unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/80unattended-upgrades
        owner: root
        group: root
        mode: 0644

    - name: "Check if {{ msehrPath }} folder exist"
      stat:
        path: "{{ msehrPath }}/public_html"
      register: msehr

    - name: "Get MedShakeEHR package v{{ msehr_base_release }}"
      get_url:
        url: "{{ msehr_base_repo_url }}v{{ msehr_base_release }}"
        dest: "/tmp/msehr.tar.gz"
        checksum: "{{ msehr_base_checksum }}"
      when: not msehr.stat.exists

    - name: Extract MedShakeEHR package
      unarchive:
        src: "/tmp/msehr.tar.gz"
        remote_src: true
        dest: "/tmp/"
      when: not msehr.stat.exists

    - name: Install MedShakeEHR file
      copy:
        remote_src: true
        src: "/tmp/MedShakeEHR-base-{{ msehr_base_release }}/"
        dest: "{{ msehrPath }}"
        mode: "u=rwX,go=rX"
        owner: www-data
        group: www-data
      when: not msehr.stat.exists

    - name: "Composer upgrade on {{ msehrPath }}"
      shell: cd "{{ msehrPath }}" && composer upgrade --no-cache
      become: true
      become_user: www-data

    - name: "Composer upgrade on {{ msehrPath }}/public_html"
      shell: cd "{{ msehrPath }}/public_html" && composer upgrade --no-cache
      become: true
      become_user: www-data

    - name: Register php version
      shell: 'php -r "echo PHP_VERSION;" | cut -c1-3'
      register: php_version

    - name: Setup php.ini configuration.
      template:
        src: templates/30-custom-php.ini.j2
        dest: "/etc/php/{{ php_version.stdout }}/apache2/conf.d/30-custom-php.ini"
        owner: root
        group: root
        mode: 0644

    - name: "Creates SSL {{ domain }} directory"
      file:
        path: "/etc/ssl/{{ domain }}"
        state: directory
        recurse: true
        owner: root
        group: root
        mode: '0755'

    - name: "Create {{ domain }} private key"
      openssl_privatekey:
        path: "/etc/ssl/{{ domain }}/{{ domain }}.key"
        size: 4096
        state: present

    - name: "Generate an OpenSSL Certificate Signing Request with Subject information for {{ domain }}"
      openssl_csr:
        path: "/etc/ssl/{{ domain }}/{{ domain }}.csr"
        privatekey_path: "/etc/ssl/{{ domain }}/{{ domain }}.key"
        country_name: "{{ countryName }}"
        locality_name: "{{ localityName }}"
        organization_name: "{{ organizationName }}"
        email_address: "{{ emailAdress }}"
        common_name: "{{ domain }}"
        subject_alt_name: 'DNS:"{{ domain }}"'
        state: present

    - name: "Generate a Self Signed OpenSSL certificate for {{ domain }}"
      openssl_certificate:
        path: "/etc/ssl/{{ domain }}/{{ domain }}.pem"
        privatekey_path: "/etc/ssl/{{ domain }}/{{ domain }}.key"
        csr_path: "/etc/ssl/{{ domain }}/{{ domain }}.csr"
        provider: selfsigned
        selfsigned_not_after: +3650d
        state: present

    - name: "Setup {{ domain }} vhosts configuration."
      template:
        src: templates/msehr.vhost.conf.j2
        dest: "/etc/apache2/sites-available/{{ domain }}.conf"
        owner: root
        group: root
        mode: 0644

    - name: Enabled mod_rewrite, mod_headers and mod_ssl
      apache2_module:
        state: present
        name: "{{ item }}"
      with_items:
        - headers
        - rewrite
        - ssl
      notify: Restart Apache

    - name: dest:eregister default vhosts
      command: a2dissite {{item}}
      with_items:
        - 000-default.conf
        - default-ssl.conf
      notify: Restart Apache

    - name: "Register {{ domain }} vhosts"
      command: a2ensite {{item}}
      with_items:
        - "{{ domain }}"
      notify: Restart Apache

    - name: Set ServerTokens Prod
      lineinfile:
        path: /etc/apache2/conf-available/security.conf
        regexp: '^ServerTokens OS'
        line: ServerTokens Prod
        state: present
      notify: Restart Apache

    - name: Set ServerSignature Off
      lineinfile:
        path: /etc/apache2/conf-available/security.conf
        regexp: '^ServerSignature On'
        line: ServerSignature Off
        state: present
      notify: Restart Apache

    - name: Set the root password
      mysql_user: login_user=root login_password="{{ sqlRootPassword }}" user=root password="{{ sqlRootPassword }}"

    - name: Secure the root user for IPV6 localhost (::1)
      mysql_user: login_user=root login_password="{{ sqlRootPassword }}" user=root password="{{ sqlRootPassword }}" host="::1"

    - name: Secure the root user for IPV4 localhost (127.0.0.1)
      mysql_user: login_user=root login_password="{{ sqlRootPassword }}" user=root password="{{ sqlRootPassword }}" host="127.0.0.1"

    - name: Secure the root user for localhost domain
      mysql_user: login_user=root login_password="{{ sqlRootPassword }}" user=root password="{{ sqlRootPassword }}" host="localhost"

    - name: Secure the root user for server_hostname domain
      mysql_user: login_user=root login_password="{{ sqlRootPassword }}" user=root password="{{ sqlRootPassword }}" host="{{ ansible_fqdn }}"

    - name: Deletes anonymous server user
      mysql_user: login_user=root login_password="{{ sqlRootPassword }}" user="" host_all=yes state=absent

    - name: Removes the test database
      mysql_db: login_user=root login_password="{{ sqlRootPassword }}" db=test state=absent

    - name: "Create {{ sqlUserAccount }} user with password and all {{ sqlDbName }} database privileges and 'WITH GRANT OPTION'"
      mysql_user:
        name: "{{ sqlUserAccount }}"
        password: "{{ sqlUserPassword }}"
        login_user: root
        login_password: "{{ sqlRootPassword }}"
        priv: "{{ sqlDbName }}.*:ALL,GRANT"
        state: present

    - name: Ensure MedShakeEHR database is present.
      mysql_db:
        name: "{{ sqlDbName }}"
        login_user: "{{ sqlUserAccount }}"
        login_password: "{{ sqlUserPassword }}"
        collation: utf8_general_ci
        encoding: utf8
        state: present

    - name: Execute MedShakeEHR cli installation script
      shell: "/usr/bin/php {{ msehrPath }}/public_html/install.php -s localhost -N -d {{ sqlDbName }} -u {{ sqlUserAccount }} -p \"{{ sqlUserPassword }}\" -r https -D {{ domain }} -o localhost"
      become: true
      become_user: www-data
      environment:
        MEDSHAKEEHRPATH: "{{ msehrPath }}"
      args:
        creates: /opt/ehr/config/config.yml

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
